### ISSUE TITLE
CAN Sim Interface Stubs

### ISSUE THREAD

**Issue by hhenry01** [UBCSailbot/network_systems#16]
### Purpose

Create some basic code for the CAN Sim Interface.

**Comment by colinli02** [comment]
Current status on branch:
- Subscribes to topic /Simulator (control will be publishing to that)

**Comment by colinli02** [comment]
## Relevant Branches:
[user/colinli02/16-CAN-Sim-Interface-Stubs](https://github.com/UBCSailbot/network_systems/tree/user/colinli02/16-CAN-Sim-Interface-Stubs)

## Current Progress:
Subscribes to ROS topic /Simulator, there is no timer because subscriber will respond to whatever published data.
Looking into logging
Communicate with CTRL team to define other topics required


Note: No more virtual CAN bus. So send between can transceiver internally on CAN.

**Comment by colinli02** [comment]
# Known bugs / notes that may be useful in future
`void timer_callback` under publisher (can_transceiver_ros_intf.cpp)
- for loop causes stuck here, maybe have to do separate timer_callback
- Possible solution: just hard code [1]. [2], .... etc.
-
Subscriber callback print not working when `ros2 run network_systems can_transceiver`
- boat_simulator (subscriber end) is not running, won't print anything (Even just normal print without any variables)

**Comment by colinli02** [comment]
# Current Status
- Both publisher and subscriber working (except one small thing with uint8 and uint64 data types) when running network_systems on ros2
- Need to fix a bit of read-ability
